# Site settings
title: Brian Lam's Haven
description: My Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://brianlam.com

# User settings
username: Brian Lam
user_description: Hey! I am a Computer Science student at the University of California - San Diego, and also a software engineer. I'm 
always on the lookout for new challenges and projects to tackle, especially ones that allow me to learn all sorts of new technologies! 
Lately, I have been focusing on back-end development for numerous side projects, building RESTful API's, testing routes, and writing documentation for all future developers, 
though I have also worked on full-stack - mixing both back-end and front-end development for some projects.
user_title: Software Engineer
email: brilam8@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
